# Generated by Django 3.0.4 on 2020-03-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs_in_a_nutshell', '0002_auto_20200330_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='color',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='shoe_type',
        ),
        migrations.DeleteModel(
            name='Manufacturer',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
        migrations.DeleteModel(
            name='ShoeColor',
        ),
        migrations.DeleteModel(
            name='ShoeType',
        ),
    ]
